/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seguradora.VIEW;

import java.sql.*; // incluido para relatório clientes
import javax.swing.JOptionPane;
import seguradora.DAL.ModuloConexao; // incluido para relatório clientes
import seguradora.VIEW.TelaAutomovel;
import seguradora.VIEW.TelaCliente;
import seguradora.VIEW.TelaOcorrencia;
import java.sql.*; // incluido para relatório clientes
import javax.swing.JOptionPane;
//import jxl.common.Logger;
import net.sf.jasperreports.engine.JasperFillManager; // incluido para relatório clientes
import net.sf.jasperreports.engine.JasperPrint; // incluido para relatório clientes
import net.sf.jasperreports.view.JasperViewer;

public class Principal extends javax.swing.JFrame {

    Connection conexao = null;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        conexao = ModuloConexao.conector();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JdpPrincipal = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        TelaClienteCadastrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        TelaAutomovel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        TelaOcorrencia = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuSobre = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seguradora de Automóveis - SENAI 2021");
        setMinimumSize(new java.awt.Dimension(750, 500));
        setResizable(false);

        JdpPrincipal.setMaximumSize(new java.awt.Dimension(750, 585));
        JdpPrincipal.setMinimumSize(new java.awt.Dimension(750, 500));
        JdpPrincipal.setPreferredSize(new java.awt.Dimension(750, 585));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seguradora/VIEW/img_apresentação.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(750, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(750, 500));
        jLabel2.setPreferredSize(new java.awt.Dimension(750, 500));

        JdpPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JdpPrincipalLayout = new javax.swing.GroupLayout(JdpPrincipal);
        JdpPrincipal.setLayout(JdpPrincipalLayout);
        JdpPrincipalLayout.setHorizontalGroup(
            JdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JdpPrincipalLayout.setVerticalGroup(
            JdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JdpPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(0, 0));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(0, 0));

        jMenu1.setBorder(null);
        jMenu1.setText("Clientes");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        TelaClienteCadastrar.setText("Tela Cliente");
        TelaClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaClienteCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(TelaClienteCadastrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(null);
        jMenu2.setText("Automóvel");

        TelaAutomovel.setText("Tela Automóvel");
        TelaAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaAutomovelActionPerformed(evt);
            }
        });
        jMenu2.add(TelaAutomovel);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(null);
        jMenu3.setText("Ocorrências");

        TelaOcorrencia.setText("Tela Ocorrência");
        TelaOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaOcorrenciaActionPerformed(evt);
            }
        });
        jMenu3.add(TelaOcorrencia);

        jMenuBar1.add(jMenu3);

        jMenu4.setBorder(null);
        jMenu4.setText("Sobre");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        MenuSobre.setText("Ajuda");
        MenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSobreActionPerformed(evt);
            }
        });
        jMenu4.add(MenuSobre);

        jMenuItem4.setText("Info");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Gerar Relatório");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        menuCliente.setText("Clientes - Automóveis");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu5.add(menuCliente);

        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Automoveis");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Ocorrências");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TelaAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaAutomovelActionPerformed
        // TODO add your handling code here:
        TelaAutomovel automovel = new TelaAutomovel();
        JdpPrincipal.add(automovel);
        automovel.setVisible(true);
    }//GEN-LAST:event_TelaAutomovelActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void TelaClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaClienteCadastrarActionPerformed
        // TODO add your handling code here:

        TelaCliente cliente = new TelaCliente(); //TelaClienteCad foi a tela criada  para cadastro de clientes usado JINTERNALFRAME
        JdpPrincipal.add(cliente); // tela principal criado dentro do Formulário USEI JPANEL DESKTOP
        cliente.setVisible(true);

    }//GEN-LAST:event_TelaClienteCadastrarActionPerformed

    private void TelaOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaOcorrenciaActionPerformed
        // TODO add your handling code here:
        TelaOcorrencia ocorrencia = new TelaOcorrencia();
        JdpPrincipal.add(ocorrencia);
        ocorrencia.setVisible(true);
    }//GEN-LAST:event_TelaOcorrenciaActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void MenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSobreActionPerformed
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("cmd /c start " + System.getProperty("user.dir") + "/SEGURADORA.chm");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_MenuSobreActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma impressão?", "", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {                                           //C:/Rel/RelClientes_Aut.jasper    
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\AliançaTech\\OneDrive\\Documentos\\Senai\\SEGURADORA/RelCliAut.jasper", null, conexao);
                //  Coloque seu relatório no caminho acima e uma cópia dentro projeto documents
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_menuClienteActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma impressão?", "", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {                                           //C:/Rel/RelClientes_Aut.jasper    
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\AliançaTech\\OneDrive\\Documentos\\Senai\\SEGURADORA/clientes.jasper", null, conexao);
                //  Coloque seu relatório no caminho acima e uma cópia dentro projeto documents
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma impressão?", "", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {                                           //C:/Rel/RelClientes_Aut.jasper    
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\AliançaTech\\OneDrive\\Documentos\\Senai\\SEGURADORA/automovel.jasper", null, conexao);
                //  Coloque seu relatório no caminho acima e uma cópia dentro projeto documents
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma impressão?", "", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {                                           //C:/Rel/RelClientes_Aut.jasper    
                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\AliançaTech\\OneDrive\\Documentos\\Senai\\SEGURADORA/ocorrencia.jasper", null, conexao);
                //  Coloque seu relatório no caminho acima e uma cópia dentro projeto documents
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }                                         
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Senai - 2021 -  Copyright(2021)  Erick Sousa Saraiva ", "PROJETO SEGURADORA", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JdpPrincipal;
    private javax.swing.JMenuItem MenuSobre;
    private javax.swing.JMenuItem TelaAutomovel;
    private javax.swing.JMenuItem TelaClienteCadastrar;
    private javax.swing.JMenuItem TelaOcorrencia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuCliente;
    // End of variables declaration//GEN-END:variables
}
